name: Add version tag

on:
  push:
    branches:
      - master
    paths:
      - conf.d/pure.fish

jobs:
  add-version-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - uses: butlerlogic/action-autotag@stable
        with:
          root: "./conf.d/pure.fish"
          regex_pattern: "pure_version\\s(?<version>(\\d+(\\.)?){3})"
          tag_prefix: "v"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
