name: Test on Alpine

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: false

jobs:
  test-container:
    name: Test `pure` with Fish ${{ matrix.version.fish }} on Alpine
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [
            { fish: 3.3.1, alpine: 3.15 }, # for Ubuntu 22.04 LTS, end 01 Apr 2027
            { fish: 3.7.1, alpine: 3.21 },
            { fish: 4.0.2, alpine: 3.22 },
            { fish: 4.2.1, alpine: "edge" },
            # { fish: 9.9.9, alpine: 'edge' },
          ]
    steps:
      - run: docker --version

      - uses: actions/checkout@v4

      - name: Debug
        run: echo  ${{ vars.TMATE_TIMEOUT && fromJSON(vars.TMATE_TIMEOUT) || 5 }}

      - name: Debug with tmate (SSH Access)
        uses: mxschmitt/action-tmate@v3
        if: failure() || inputs.debug_enabled == true
        with:
          detached: true
        timeout-minutes: ${{ vars.TMATE_TIMEOUT && fromJSON(vars.TMATE_TIMEOUT) || 5 }}
        continue-on-error: true

      - name: Build Pure Image on Alpine ${{ matrix.version.alpine }}
        run: make build-pure-on FISH_VERSION=${{ matrix.version.fish }}

      - name: Run Tests
        run: make test-pure-on FISH_VERSION=${{ matrix.version.fish }}
